CREATE TABLE IF NOT EXISTS RECIPE(
	ID IDENTITY PRIMARY KEY,
	NAME VARCHAR (100) NOT NULL  ,
	DESCRIPTION VARCHAR (500) NOT NULL,
	FOOD_TYPE VARCHAR (50) NOT NULL,
	SERVED_TO INT NOT NULL,
	CREATED_ON TIMESTAMP
	);
	
CREATE TABLE IF NOT EXISTS INSTRUCTIONS(
	INSTRUCTION_ID IDENTITY PRIMARY KEY,
	INSTRUCTION_DESCRIPTION VARCHAR(500) NOT NULL,
	RECIPE_ID INT,
	FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(ID)
	);
	
CREATE TABLE IF NOT EXISTS INGREDIENTS(
	INGREDIENT_ID IDENTITY PRIMARY KEY,
	INGREDIENT_NAME VARCHAR(500) NOT NULL,
	RECIPE_ID INT,
	FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(ID)
	);



INSERT INTO 
	RECIPE (NAME, DESCRIPTION, FOOD_TYPE, SERVED_TO, CREATED_ON) 
VALUES
  	('GARLIC DIP', 'GARLIC DIP', 'VEGETARIAN', 2, CURRENT_TIMESTAMP());
  	
 INSERT INTO 
 	INGREDIENTS (INGREDIENT_NAME, RECIPE_ID)
 	VALUES ('2 cups cooked or canned (no BPA) garbanzo beans', 1);
 INSERT INTO 
 	INGREDIENTS (INGREDIENT_NAME, RECIPE_ID)
 	VALUES ('1 TBS fresh lemon juice;3 cloves garlic, chopped', 1);
 INSERT INTO 
 	INGREDIENTS (INGREDIENT_NAME, RECIPE_ID)
 	VALUES ('1/4 cup chicken or vegetable broth', 1);
 INSERT INTO 
 	INGREDIENTS (INGREDIENT_NAME, RECIPE_ID)
 	VALUES ('3 TBS extra virgin olive oil', 1);
 	
 INSERT INTO 
 	INSTRUCTIONS (INSTRUCTION_DESCRIPTION, RECIPE_ID)
 	VALUES ('Combine all ingredients in a blender and blend until smooth', 1);